### ISSUE TITLE
dispatchTouchEvent数组越界java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhangmeie2006** [donkingliang/ConsecutiveScroller#209]
4.5.1版本ConsecutiveScrollerLayout类655行出现异常程序退出了，需要捕获下
boolean dispatch = super.dispatchTouchEvent(ev);
java.lang.ArrayIndexOutOfBoundsException: length=24; index=-1
	at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3546)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2574)
	at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.dispatchTouchEvent(ConsecutiveScrollerLayout.java:643)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.dispatchTouchEvent(SwipeToLoadLayout.java:453)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2974)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2604)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:549)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1953)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3559)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:502)
	at android.view.View.dispatchPointerEvent(View.java:12027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5304)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5093)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4641)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4607)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4734)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4615)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4791)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4641)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4607)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4615)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4588)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7195)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7169)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7130)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7351)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:379)
	at android.os.Looper.loop(Looper.java:144)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by donkingliang** [comment]
这个问题在4.5.2版本已修复

**Comment by zhangmeie2006** [comment]
> 这个问题在4.5.2版本已修复
好的👌
