### ISSUE TITLE
有个死循环

### ISSUE THREAD

**Issue by openproject** [donkingliang/ConsecutiveScroller#216]
DALVIK THREADS (164):
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x72f425a8 self=0xb400007913010800
  | sysTid=28225 nice=-10 cgrp=default sched=0/0 handle=0x799a36a500
  | state=R schedstat=( 27734626424 167586488 3180 ) utm=2684 stm=88 core=6 HZ=100
  | stack=0x7fda1f0000-0x7fda1f2000 stackSize=8192KB
  | held mutexes= "mutator lock"(shared held)
  at android.view.View.findViewById(View.java:25238)
  at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4818)
  at android.view.View.findViewById(View.java:25241)
  at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4818)
  at android.view.View.findViewById(View.java:25241)
  at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4818)
  at android.view.View.findViewById(View.java:25241)
  at android.view.ViewGroup.findViewTraversal(ViewGroup.java:4818)
  at android.view.View.findViewById(View.java:25241)
  at com.donkingliang.consecutivescroller.ScrollUtils.getScrollChild(ScrollUtils.java:362)
  at com.donkingliang.consecutivescroller.ScrollUtils.getScrolledView(ScrollUtils.java:336)
  at com.donkingliang.consecutivescroller.ScrollUtils.computeVerticalScrollExtent(ScrollUtils.java:66)
  at com.donkingliang.consecutivescroller.ScrollUtils.getScrollBottomOffset(ScrollUtils.java:108)
  at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.scrollUp(ConsecutiveScrollerLayout.java:1108)
  at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.dispatchScroll(ConsecutiveScrollerLayout.java:1059)
  at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.scrollToChildWithOffset(ConsecutiveScrollerLayout.java:2161)
  at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.scrollToChild(ConsecutiveScrollerLayout.java:2121)

getScrollBottomOffset 返回 1 导致退不出 do {} while (scrollOffset > 0 && remainder > 0) 循环

**Comment by donkingliang** [comment]
死循环的问题在4.5.3版本已解决，你尝试一下。

**Comment by openproject** [comment]
我用的就是 4.5.3 版本

**Comment by donkingliang** [comment]
> 我用的就是 4.5.3 版本
你能提供个demo吗？

**Comment by donkingliang** [comment]
> 我用的就是 4.5.3 版本

你能提供个重现问题的demo吗？
