### ISSUE TITLE
嵌套smaltable的时候smaltable得滚动完毕才能往上滑动，否则一直是固定的smalltable高度滑动完了才到下一屏幕

### ISSUE THREAD

**Issue by qssq** [donkingliang/ConsecutiveScroller#228]
其实我主要不是用来做吸顶用的，只是coordiatelayout和smalltable 使用触摸头部有时候无法滑动 出现了问题我才不得已使用了这个。
触摸smalltable是必须等smalltable滑动到底才行，但是触摸头部就可以把smalltable划过去。

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data></data>

    <com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout
        android:id="@+id/scrollerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical">

        <include
            android:id="@+id/header_fai"
            layout="@layout/view_fai_data_input_head"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:visibility="visible"

            app:layout_collapseMode="parallax" />

<!--        <xxxn.app.ui.thrid.MySmartTable-->
        <com.bin.david.form.core.SmartTable
            android:id="@+id/tableview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout>
</layout>
```
不使用nestedhelper问题一样存在

**Comment by qssq** [comment]
```

public class MySmartTable  extends SmartTable implements NestedScrollingChild {

    public static final String TAG = MySmartTable.class.getSimpleName();

    private int mLastMotionY;

    private final int[] mScrollOffset = new int[2];
    private final int[] mScrollConsumed = new int[2];

    private int mNestedYOffset;

    private NestedScrollingChildHelper mChildHelper;

    public MySmartTable(Context context) {
        super(context);
        init();
    }

    public MySmartTable(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public MySmartTable(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    private void init() {
        mChildHelper = new NestedScrollingChildHelper(this);
        setNestedScrollingEnabled(true);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        boolean result = false;

        MotionEvent trackedEvent = MotionEvent.obtain(event);

        final int action =event.getActionMasked();// MotionEvent.getActionMasked(event); masked解决多指触摸bug.

        if (action == MotionEvent.ACTION_DOWN) {
            mNestedYOffset = 0;
        }
        int y = (int) event.getY();
        event.offsetLocation(0, mNestedYOffset);

        switch (action) {
            case MotionEvent.ACTION_DOWN:
                mLastMotionY = y;
                startNestedScroll(ViewCompat.SCROLL_AXIS_VERTICAL);
                result = super.onTouchEvent(event);
                break;
            case MotionEvent.ACTION_MOVE:
                int deltaY = mLastMotionY - y;

                if (dispatchNestedPreScroll(0, deltaY, mScrollConsumed, mScrollOffset)) {
                    deltaY -= mScrollConsumed[1];
                    trackedEvent.offsetLocation(0, mScrollOffset[1]);
                    mNestedYOffset += mScrollOffset[1];
                }

                int oldY = getScrollY();
                mLastMotionY = y - mScrollOffset[1];
                if (deltaY < 0) {
                    int newScrollY = Math.max(0, oldY + deltaY);
                    deltaY -= newScrollY - oldY;
                    if (dispatchNestedScroll(0, newScrollY - deltaY, 0, deltaY, mScrollOffset)) {
                        mLastMotionY -= mScrollOffset[1];
                        trackedEvent.offsetLocation(0, mScrollOffset[1]);
                        mNestedYOffset += mScrollOffset[1];
                    }
                }else{//解决 只能隐藏却无法显示问题。
                    int newScrollY = Math.min(0, oldY + deltaY);
                    deltaY -= newScrollY - oldY;
                    if (dispatchNestedScroll(0, newScrollY - deltaY, 0, deltaY, mScrollOffset)) {
                        mLastMotionY -= mScrollOffset[1];
                        trackedEvent.offsetLocation(0, mScrollOffset[1]);
                        mNestedYOffset += mScrollOffset[1];
                    }
                }

                trackedEvent.recycle();
                result = super.onTouchEvent(trackedEvent);
                break;
            case MotionEvent.ACTION_POINTER_DOWN:
            case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_CANCEL:
                stopNestedScroll();
                result = super.onTouchEvent(event);
                break;
        }
        return result;
    }
    //todo 导出待做

    // NestedScrollingChild

    @Override
    public void setNestedScrollingEnabled(boolean enabled) {
        mChildHelper.setNestedScrollingEnabled(enabled);
    }

    @Override
    public boolean isNestedScrollingEnabled() {
        return mChildHelper.isNestedScrollingEnabled();
    }

    @Override
    public boolean startNestedScroll(int axes) {
        return mChildHelper.startNestedScroll(axes);
    }

    @Override
    public void stopNestedScroll() {
        if(BuildConfig.DEBUG){
            Log.w(TAG,"STOP NESTED SCROLL");
        }
        mChildHelper.stopNestedScroll();
    }

    @Override
    public boolean hasNestedScrollingParent() {
        return mChildHelper.hasNestedScrollingParent();
    }

    @Override
    public boolean dispatchNestedScroll(int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed, int[] offsetInWindow) {
        return mChildHelper.dispatchNestedScroll(dxConsumed, dyConsumed, dxUnconsumed, dyUnconsumed, offsetInWindow);
    }

    @Override
    public boolean dispatchNestedPreScroll(int dx, int dy, int[] consumed, int[] offsetInWindow) {
        return mChildHelper.dispatchNestedPreScroll(dx, dy, consumed, offsetInWindow);
    }

    @Override
    public boolean dispatchNestedFling(float velocityX, float velocityY, boolean consumed) {
        return mChildHelper.dispatchNestedFling(velocityX, velocityY, consumed);
    }

    @Override
    public boolean dispatchNestedPreFling(float velocityX, float velocityY) {
        return mChildHelper.dispatchNestedPreFling(velocityX, velocityY);
    }

}
```
不知道是哪里写错了

**Comment by qssq** [comment]
不过总比无法滑动头部的好，因为头部是一个很长的表单有些手机可能看不到smalltable，这问题非常致命，使用你的这个，效果还不算太差。

**Comment by qssq** [comment]
我的coordinatelayout include其实是包含了横屏和竖屏布局，应该和这没关系吧，我include另外一个头部就没bug,include这个就有问题，我搞了一天没搞出来是哪里导致的，到底是smalltable写的嵌套有问题还是头部有什么东西。

**Comment by donkingliang** [comment]
我不太明白你所表述的问题。你能详细表述一下你想实现的效果和目前遇到的问题吗？最好能提供一个你遇到问题的demo给我，能方便我理解和定位问题。

**Comment by qssq** [comment]
这个布局包含一个头部和表格，滑动头部是可以把表格也滑动上去的，但是触摸的不是头部而是表格，问题就来了，表格内部在滑动，并没有带动头部一起网上滚，直到表格滑动到底部了，才把头部给滑动没

**Comment by qssq** [comment]
https://user-images.githubusercontent.com/14260426/140674744-11e4570d-8916-4ed0-9718-0b557f3023b8.mp4

这就是复现视频

**Comment by qssq** [comment]
我明明开启了触摸反馈，这录屏软件竟然没录进去，后面部分可以看出来滑动的时候只有表格的1234** 在变化，头部没有给画上去。

**Comment by donkingliang** [comment]
我看了一下SmartTable的源码，它内部的滑动和显示是交给内部的MatrixHelper类处理的，MatrixHelper内部维护translateX、translateY来保存滑动偏移和计算显示区域。所以对于view体系来说，view的坐标和mScrollX、mScrollY是没有改变的，而ConsecutiveScroller依赖于view体系中的ScrollY处理滑动，所以SmartTable不适用于ConsecutiveScroller。

另外，SmartTable内部会禁止父view拦截事件，所以始终是先自己滑动完，才把事件交给父布局处理。如果你要改变它的拦截规则，需要重写它的方法，而这些都是交给MatrixHelper处理的，所以主要还是要重写MatrixHelper的方法，不过MatrixHelper的一下关键方法，比如判断滑动边界等是私有的，无法重写。

**Comment by qssq** [comment]
```

**Comment by qssq** [comment]
```

**Comment by qssq** [comment]
```    java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:186)
        at android.view.View.measure(View.java:23180)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1187)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:706)
        at android.view.View.measure(View.java:23180)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1168)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:706)
        at android.view.View.measure(View.java:23180)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23180)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
        at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.measureChildWithMargins(ConsecutiveScrollerLayout.java:434)
        at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.onMeasure(ConsecutiveScrollerLayout.java:345)
```
这有点头疼搞不懂今天为啥这种错误了

**Comment by donkingliang** [comment]
报的什么错误，在什么情况下报错

**Comment by qssq** [comment]
@donkingliang不好意思  打扰了，这是我自己自定义控件的问题，
