### ISSUE TITLE
只能作为根布局吗？

### ISSUE THREAD

**Issue by SherlockGougou** [donkingliang/ConsecutiveScroller#9]
我按照截图这样布局，好像会有问题，控件的内容区不可滑动，点击控件外部会闪退：

![image](https://user-images.githubusercontent.com/17920617/79091416-c2c17b80-7d7f-11ea-9cbc-3fe9c840911a.png)
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
        at com.donkingliang.consecutivescroller.ScrollUtils.isConsecutiveScrollerChild(ScrollUtils.java:188)
        at com.donkingliang.consecutivescroller.ConsecutiveScrollerLayout.dispatchTouchEvent(ConsecutiveScrollerLayout.java:172)
```

**Comment by donkingliang** [comment]
你使用的是最新的版本吗？1.2.0或者2.2.0的版本？

**Comment by SherlockGougou** [comment]
我直接用你的demo改的代码运行的。

**Comment by donkingliang** [comment]
那你可能下载的是旧的代码，旧的代码是有一点问题的，你下载新的代码试一下。
